#!/system/bin/sh

# Depending on Hardware (VV or PR board), NVRAM is different to follow the hardware.
NVRAM_REV="$(getprop ro.spid.wifi.nvram)"
if [ -z "${NVRAM_REV}" ]
then
NVRAM_REV='vv'
fi

# These hardcoded path for firmware and nvram are also defined in
# WifiBoardConfig.mk. Make sure to change at both places...
BCM43241_FLAGS="firmware_path=/system/etc/firmware/fw_bcmdhd_43241.bin nvram_path=/system/etc/wifi/bcmdhd_43241.cal"
BCM4334_FLAGS="firmware_path=/system/etc/firmware/fw_bcmdhd_4334.bin nvram_path=/system/etc/wifi/bcmdhd_4334_${NVRAM_REV}.cal"
BCM4335_FLAGS="firmware_path=/system/etc/firmware/fw_bcmdhd_4335.bin nvram_path=/system/etc/wifi/bcmdhd_4335.cal"

if [ -f /init.saltbay.rc ]; then
    setprop wlan.bcm.chip 4335
    /system/bin/insmod /lib/modules/bcm4335.ko ${BCM4335_FLAGS}
elif [ -f /init.bodegabay.rc ]; then
    setprop wlan.bcm.chip 4334
    /system/bin/insmod /lib/modules/bcm4334.ko ${BCM4334_FLAGS}
elif [ -f /init.baylake.rc ]; then
    setprop wlan.bcm.chip 43241
# Hack the gpio PCONF0 register to enable direct irq routing.
# if the driver is handling rising edge interrupts, the use 0x2d02cc01
# else 0x2b02cc01 in PCONF0 register accociated to GPIO_SUS_15
# This change configure the right polarity needed by broadcom chip.
    echo "w mmio 0xfed0e010 0x2b02cc01" > /d/dump_cmd
    cat /d/dump_output
   # Route the GPIO 15 (wlan_irq) to the direct IOAPIC interrupt pin
    echo "w mmio 0xfed0e98c 0x0f000000" > /d/dump_cmd
    cat /d/dump_output
    /system/bin/insmod /lib/modules/bcm43241.ko ${BCM43241_FLAGS}
elif [ -f /init.victoriabay.rc ]; then
    setprop wlan.bcm.chip 4334
    /system/bin/insmod /lib/modules/bcm4334.ko ${BCM4334_FLAGS}
# ctpscale platforms rely on init.redhookbay.rc. This script will not
# be executed on TI-based platform.
elif [ -f /init.redhookbay.rc ]; then
    setprop wlan.bcm.chip 4334
    /system/bin/insmod /lib/modules/bcm4334.ko ${BCM4334_FLAGS}
fi
