#!/system/bin/sh

# Depending on Hardware (VV or PR board), NVRAM is different to follow the hardware.
NVRAM_REV="$(getprop ro.spid.wifi.nvram)"
if [ -z "${NVRAM_REV}" ]
then
NVRAM_REV='vv'
fi

/system/bin/insmod /lib/modules/bcmdhd.ko firmware_path=/system/etc/firmware/fw_bcmdhd_4334.bin nvram_path=/system/etc/wifi/bcmdhd_4334_${NVRAM_REV}.cal
