include $(COMMON_PATH)/ComboChipVendor.mk

BOARD_WPA_SUPPLICANT_DRIVER    := NL80211
BOARD_HOSTAPD_PRIVATE_LIB      :=

ifeq (ti,$(findstring ti,$(COMBO_CHIP_VENDOR)))
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WLAN_DEVICE := wl12xx-compat
endif

ifeq (bcm,$(findstring bcm,$(COMBO_CHIP_VENDOR)))
endif

ifneq (,$(filter wifi_rtl%,$(PRODUCTS.$(INTERNAL_PRODUCT).PRODUCT_PACKAGES)))
BOARD_WPA_SUPPLICANT_PRIVATE_LIB += lib_driver_cmd_rtl
BOARD_HOSTAPD_DRIVER        := NL80211
BOARD_HOSTAPD_PRIVATE_LIB   += lib_driver_cmd_rtl
endif

ifeq (intel,$(findstring intel,$(COMBO_CHIP_VENDOR)))
BOARD_WLAN_DEVICE     := iwlwifi
BOARD_HOSTAPD_DRIVER  := NL80211
#WPA_SUPPLICANT_VERSION := VER_0_8_X
WPA_SUPPLICANT_VERSION := VER_2_1_DEVEL_WCS
PRIVATE_WPA_SUPPLICANT_CONF := y

# Used to compile Driver
BOARD_USING_INTEL_IWL := true
INTEL_IWL_BOARD_CONFIG := mofd_lnp
INTEL_IWL_USE_COMPAT_INSTALL := y
INTEL_IWL_USE_RM_MAC_CFG := y
endif
