#!/sbin/ash

###################################################################
# configure trace level for mts
#
# configure_trace_modem -d -t1 : HSI 78MHz, first level trace
# configure_trace_modem -d -t2 : HSI 78MHz, second level trace
# configure_trace_modem -d -t3 : HSI 78MHz, third level trace
# configure_trace_modem -h -t1 : HSI 156MHz, first level trace
# configure_trace_modem -h -t2 : HSI 156MHz, second level trace
# configure_trace_modem -h -t3 : HSI 156MHz, third level trace
# configure_trace_modem -u -t0 : HSI disabled, trace disabled
#
##################################################################

#############################
# Check numbers of arguments
#############################
if [ $# != 2 ]
then
	echo "USAGE: configure_trace_modem [-d|-h -t1|-t2|-t3]"
	echo "USAGE: configure_trace_modem [-u -t0]"
	echo "       -u: disable HSI"
	echo "       -d: default speed HSI, 78MHz"
	echo "       -h: high speed HSI, 156MHz"
	echo "       -t0: disable trace"
	echo "       -t1: first level trace (bb_sw)"
	echo "       -t2: second level trace (bb_sw & 3g_sw)"
	echo "       -t2: third level trace (bb_sw & 3g_sw & digrf)"
	exit 0
fi

##############
# Check speed
##############
if [ "$1" = "-d" ] && ( [ "$2" = "-t1" ] || [ "$2" = "-t2" ] || [ "$2" = "-t3" ] )
then
	echo "Default speed HSI 78MHz"
	echo -e -r "at+xsio=4\r\n" > /dev/gsmtty1
	sleep 1;
elif [ "$1" = "-h" ] && ( [ "$2" = "-t1" ] || [ "$2" = "-t2" ] || [ "$2" = "-t3" ] )
then
	echo "High speed HSI 156MHz"
	echo -e -r "at+xsio=5\r\n" > /dev/gsmtty1
	sleep 1;
elif [ "$1" = "-u" ] && [ "$2" = "-t0" ]
then
	echo "Disable HSI"
	echo -e -r "at+xsio=0\r\n" > /dev/gsmtty1
	sleep 1;
else
	echo "USAGE: configure_trace_modem [-d|-h -t1|-t2|-t3]"
	echo "USAGE: configure_trace_modem [-u -t0]"
	echo "       -u: disable HSI"
	echo "       -d: default speed HSI, 78MHz"
	echo "       -h: high speed HSI, 156MHz"
	echo "       -t0: disable trace"
	echo "       -t1: first level trace (bb_sw)"
	echo "       -t2: second level trace (bb_sw & 3g_sw)"
	echo "       -t2: third level trace (bb_sw & 3g_sw & digrf)"
	exit 0
fi

####################
# Check level trace
####################
if ( [ "$1" = "-d" ] || [ "$1" = "-h" ] ) && [ "$2" = "-t1" ]
then
	echo "Enable first level trace (bb_sw)"
	echo -e -r "at+trace=,115200,\"st=1,pr=1,bt=1,ap=0,db=1,lt=0,li=1,ga=0,ae=0\"\r\n" > /dev/gsmtty1 &
	sleep 1;
	echo -e -r "at+xsystrace=1,\"bb_sw=1\",,\"oct=4\"\r\n" > /dev/gsmtty1
	sleep 2;
	echo "configure_trace_modem" $1 $2 "SUCCESS. Your board need a HARDWARE reboot"
	exit 0
elif ( [ "$1" = "-d" ] || [ "$1" = "-h" ] ) && [ "$2" = "-t2" ]
then
	echo "Enable second level trace (bb_sw & 3g_sw)"
	echo -e -r "at+trace=,115200,\"st=1,pr=1,bt=1,ap=0,db=1,lt=0,li=1,ga=0,ae=0\"\r\n" > /dev/gsmtty1 &
	sleep 1;
	echo -e -r "at+xsystrace=1,\"bb_sw=1;3g_sw=1\",,\"oct=4\"\r\n" > /dev/gsmtty1 &
	sleep 2;
	echo "configure_trace_modem" $1 $2 "SUCCESS. Your board need a HARDWARE reboot"
	exit 0
elif ( [ "$1" = "-d" ] || [ "$1" = "-h" ] ) && [ "$2" = "-t3" ]
then
	echo "Enable third level trace (bb_sw & 3g_sw & digrf)"
	echo -e -r "at+trace=,115200,\"st=1,pr=1,bt=1,ap=0,db=1,lt=0,li=1,ga=0,ae=0\"\r\n" > /dev/gsmtty1 &
	sleep 1;
	echo -e -r "at+xsystrace=1,\"digrf=1;bb_sw=1;3g_sw=1\",\"digrf=0x84\",\"oct=4\"\r\n" > /dev/gsmtty1 &
	sleep 2;
	echo "configure_trace_modem" $1 $2 "SUCCESS. Your board need a HARDWARE reboot"
	exit 0
elif [ "$1" = "-u" ] && [ "$2" = "-t0" ]
then
	echo "Disable trace"
	echo -e -r "at+trace=0\r\n" > /dev/gsmtty1
	sleep 1;
	echo -e -r "at+xsystrace=0\r\n" > /dev/gsmtty1 &
	sleep 2;
	echo "configure_trace_modem" $1 $2 "SUCCESS. Your board need a HARDWARE reboot"
	exit 0
else
	echo "USAGE: configure_trace_modem [-d|-h -t1|-t2|-t3]"
	echo "USAGE: configure_trace_modem [-u -t0]"
	echo "       -u: disable HSI"
	echo "       -d: default speed HSI, 78MHz"
	echo "       -h: high speed HSI, 156MHz"
	echo "       -t0: disable trace"
	echo "       -t1: first level trace (bb_sw)"
	echo "       -t2: second level trace (bb_sw & 3g_sw)"
	echo "       -t2: third level trace (bb_sw & 3g_sw & digrf)"
	exit 0
fi
