#!/sbin/ash

#############################################
## usbswitch ape to modem
## used by service : usb_to_modem
#############################################

if [ -d /sys/class/gpio/gpio169/ ]; then
    if [ $(cat /sys/class/gpio/gpio169/value) -eq 1 ]; then
        exit 0
    else
        echo 1 > /sys/class/gpio/gpio169/value
        echo "1" > /data/data/com.intel.amtl/files/usbswitch.conf
    fi
else
    echo 169 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio169/direction
    echo 1 > /sys/class/gpio/gpio169/value
    echo "1" > /data/data/com.intel.amtl/files/usbswitch.conf
fi
