#!/sbin/ash

#############################################
## usbswitch status
## used by service : usbswitch_status
#############################################

if [ -e /sys/class/gpio/gpio169/value ]
then
    cat /sys/class/gpio/gpio169/value > /data/data/com.intel.amtl/files/usbswitch.conf
else
    echo "0" > /data/data/com.intel.amtl/files/usbswitch.conf
fi
