#!/sbin/ash

#############################################
## usbswitch ape to modem
## used by service : usb_to_modem
#############################################

echo 169 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio169/direction
echo 1 > /sys/class/gpio/gpio169/value
echo "1" > /data/data/com.intel.amtl/files/usbswitch.conf
